### ISSUE TITLE
Support for *.SLNX files

### ISSUE THREAD

**Issue by MovGP0** [dotnet-outdated/dotnet-outdated#614]
There is currenly no support for `*.slnx` files ([Medium: Welcome to the new Visual Studio SLNX Solution File](https://medium.com/medialesson/welcome-to-the-new-visual-studio-slnx-solution-file-3c20d37a1cb3)).

It's currenly a preview feature. Given that the file format is reasonably simple it should not be too complex to implement. 

### Current behavior

```shell
❯ dotnet outdated
Discovering projects...The directory 'c:\xxxx' does not contain any solutions or projects.
```

**Comment by WeihanLi** [comment]
msbuild & dotnet-cli already added support for the slnx since `9.0.200`

https://github.com/dotnet/msbuild/issues/10266
https://github.com/dotnet/sdk/issues/40913

**Comment by molostovvs** [comment]
@slang25 
It seems this issue can be closed, as https://github.com/dotnet-outdated/dotnet-outdated/pull/652 has implemented .slnx support

**Comment by Daeer-Projects** [comment]
Although dotnet and MSBuild now support the new `.slnx` file type, my build on Azure doesn't work.

* dotnet: 9.0.202.
* dotnet-outdated: 4.6.8
* Command: "C:\BuildAgent\_work\_tool\dotnet\dotnet.exe dotnet-outdated C:\BuildAgent\_work\4\s\Alchemy.slnx -n -u -t -vl Major"
* Error: "Discovering projects...The file 'C:\BuildAgent\_work\4\s\Alchemy.slnx' is not a valid solution or project."

My other build scripts work. This build is to automatically update packages and is the only one that doesn't work, not that we have moved to the new `.slnx` solution file type.

Can you help me? Have I got part of the command wrong?

From our `.yml` file:
```
- task: DotNetCoreCLI@2
  displayName: 'Update Nuget'
  timeoutInMinutes: 120
  inputs:
    command: 'custom'
    custom: 'dotnet-outdated'
    projects: '$(solution)'
    arguments: '-n -u -t -vl Major'
```
