### ISSUE TITLE
When running concurrent jobs in Azure Pipelines only macOS-10.15 agent seems to run dotnet outdated correctly

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [dotnet-outdated/dotnet-outdated#63]
# Description
I have a github project: [Minicloner](https://github.com/carlosmunozrodriguez/Minicloner) that is set up to build in Azure Pipelines using YAML that runs `dotnet outdated --fail-on-updates` to make the build fail if there are packages that needs to be updated.
It is using `strategy: matrix:` to make parallel builds with different OS.

In the following run: https://dev.azure.com/carlosmunozrodriguez/Minicloner/_build/results?buildId=409&view=results there are 3 parallel builds with the following OS: `windows-2019`, `ubuntu-18.04` and `macOS-10.15`.

From them only `macOS-10.15` seems to be failing as expected with error code: 2  and showing which packages need to be updated as can be seen in the log: https://dev.azure.com/carlosmunozrodriguez/Minicloner/_build/results?buildId=409&view=logs&j=9dfcfd74-a2de-5bf2-9e58-61496624eb87&t=97b4bd01-7b13-5e1f-aec9-981abf187912

The other two OSs fail to run `dotnet outdated --fail-on-updates` and fail (wrongly) with error code: 1 (or -1 I'm not sure), complaining about the `.sln` file format and not showing any package to be updated as can be seen in https://dev.azure.com/carlosmunozrodriguez/Minicloner/_build/results?buildId=409&view=logs&j=a5ebbe75-5229-5b14-a2b3-c71e02a6da90&t=66e992de-13e4-504c-5081-8f9683287dd0 and https://dev.azure.com/carlosmunozrodriguez/Minicloner/_build/results?buildId=409&view=logs&j=630ea742-76aa-511f-2933-7f478559492b&t=b9a36882-b809-52fe-18e3-8dfc925d8ff5

The relevant portion of `azure-pipelines.yaml` is here:

```yaml
jobs:
- job: Build

# Image names can be get from: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
  strategy:
    matrix:
      Windows:
        imageName: 'windows-2019'
      Ubuntu-18.04:
        imageName: 'ubuntu-18.04' # ubuntu-20.04 doesn't support net core sdk 1.1'
      macOS:
        imageName: 'macOS-10.15'

  pool:
    vmImage: $(imageName)

  steps:
  - task: UseDotNet@2
    displayName: 'Install older dotnet 1.1 runtime'
    inputs:
      packageType: 'runtime'
      version: '1.1.13'

  - task: UseDotNet@2
    displayName: 'Install older dotnet 2.2 runtime'
    inputs:
      packageType: 'runtime'
      version: '2.2.8'

  - task: UseDotNet@2
    displayName: 'Install older dotnet 3.1 runtime'
    inputs:
      packageType: 'runtime'
      version: '3.1.10'

  - task: UseDotNet@2
    displayName: 'Install current dotnet SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet --info'
    inputs:
      command: 'custom'
      custom: '--info'

  - task: DotNetCoreCLI@2
    displayName: 'Install dotnet-outdated'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global dotnet-outdated-tool'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet outdated'
    inputs:
      command: 'custom'
      custom: 'outdated'
      arguments: '--fail-on-updates'

```

Other things to consider

The solution contains multitargeting projects
There are many runtimes installed and one latest SDK
